"""The training loop: rollouts in, one Tinker clock cycle out.

One step, in the order it happens and the order it must happen in:

1. **Sync the sampler** every ``train.sync_sampler_every`` steps, so rollouts come from
   something close to the current policy. (GFlowNet objectives do not *need* this — they
   are off-policy-consistent — but a sampler drifting arbitrarily far behind wastes the
   exploration budget on a policy nobody is training.)
2. **Roll out** ``groups_per_step`` prompts x ``group_size`` completions and score them.
3. **Mix in replay**, if enabled. The buffer is sampled *before* this step's rollouts are
   added to it, so replay is genuinely off-policy rather than partly a copy of the fresh
   batch.
4. **Get current-policy logprobs.** Either the ``forward()`` oracle
   (:meth:`~flowcode.tinker_backend.TinkerBackend.compute_logprobs`), or — under
   ``train.on_policy_only`` — the sampler's own logprobs, which skips a whole forward pass
   over every token in the batch and halves the training-token bill exactly.
5. **Loss and backward**, entirely client-side.
6. **Push the gradient, then step**, in that order and with ``defer=True``, so the
   ``forward_backward`` and the ``optim_step`` land in one server clock cycle instead of
   two. Reversing them, or draining the backward first, doubles the per-step latency for
   no other change.
7. **Step the local optimiser** for the objective's ``log Z`` / ``log F`` parameters. These
   live in this process (see :mod:`flowcode.objectives.flows`) and get their own Adam at
   ``train.flow_lr``, which is conventionally 100-1000x the policy LR.

``on_policy_only`` + ``replay.enabled`` is incoherent
-----------------------------------------------------
``on_policy_only`` means "the sampler's logprobs *are* the current policy's logprobs".
A replayed trajectory was generated by an older policy, so its stored logprobs are not the
current policy's and never will be. Training on them regresses the balance conditions
against the wrong ``log P_F``, which does not raise, does not look wrong in the metrics,
and quietly optimises the wrong thing. :func:`validate_train_config` rejects the
combination before a single dollar is spent.

Money
-----
The loop prints :func:`flowcode.cost.estimate` up front and
:func:`flowcode.cost.from_usage` at the end, and the final report is emitted from a
``finally``: a run that dies at step 700 of 1000 has still spent 70% of the estimate, and
that number must not die with the traceback.
"""

from __future__ import annotations

import logging
import math
import os
import random
import re
from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Any, Final, Protocol

import torch
from hydra.utils import instantiate
from omegaconf import DictConfig, OmegaConf

from flowcode.checkpoint import (
    RunState,
    load_run_state,
    restore_flow_parameters,
    save_run_state,
)
from flowcode.config import ModelConfig, RootConfig, get_api_key, get_project_id
from flowcode.cost import CostEstimate, estimate, from_usage
from flowcode.envs.base import Environment, Task
from flowcode.envs.datasets import split_tasks
from flowcode.logging import RunLogger, make_logger
from flowcode.objectives.base import Objective
from flowcode.producer import TrajectoryProducer
from flowcode.render import ChatTokenizer
from flowcode.replay import ReplayBuffer
from flowcode.rollout import RolloutStats, rollout
from flowcode.tinker_backend import TinkerBackend
from flowcode.types import (
    SampleResponse,
    SamplingParams,
    TokenUsage,
    Trajectory,
    TrajectoryBatch,
)

__all__ = [
    "EVAL_MAX_TASKS",
    "LR_SCHEDULES",
    "BackendLike",
    "Trainer",
    "learning_rate",
    "train",
    "validate_train_config",
]

logger = logging.getLogger(__name__)

LR_SCHEDULES: Final[tuple[str, ...]] = ("linear", "cosine", "constant")
"""Legal values of ``train.lr_schedule``."""

EVAL_MAX_TASKS: Final[int] = 32
"""Cap on held-out tasks scored per eval.

Evals are sampled and scored like any other rollout, i.e. they cost money, and
``TrainConfig`` has no knob for their size. The cap is applied to a ``task_id``-sorted
list, so the same tasks are evaluated at every eval of every run and the pass rates are
comparable across steps."""

_NAME_SAFE = re.compile(r"[^A-Za-z0-9._-]+")


class BackendLike(Protocol):
    """The slice of :class:`~flowcode.tinker_backend.TinkerBackend` the loop drives.

    Structural, so the offline tests can substitute a fake that returns canned logprobs
    and records call order — which is how "apply_gradient before optim_step" is asserted
    without spending anything.
    """

    model_cfg: ModelConfig

    async def sample(
        self,
        prompts: Sequence[Sequence[int]],
        num_samples: int,
        sampling_params: SamplingParams,
    ) -> list[SampleResponse]:
        """See :meth:`flowcode.rollout.SamplerLike.sample`."""
        ...

    async def compute_logprobs(self, trajectories: TrajectoryBatch) -> list[torch.Tensor]:
        """See :meth:`flowcode.tinker_backend.TinkerBackend.compute_logprobs`."""
        ...

    async def apply_gradient(
        self,
        trajectories: TrajectoryBatch,
        grads: Sequence[torch.Tensor],
        *,
        grad_scale: float = 1.0,
        defer: bool = False,
    ) -> dict[str, float]:
        """See :meth:`flowcode.tinker_backend.TinkerBackend.apply_gradient`."""
        ...

    async def optim_step(self, lr: float, *, grad_clip_norm: float = 0.0) -> dict[str, float]:
        """See :meth:`flowcode.tinker_backend.TinkerBackend.optim_step`."""
        ...

    async def sync_sampler(self) -> None:
        """See :meth:`flowcode.tinker_backend.TinkerBackend.sync_sampler`."""
        ...

    def token_usage(self) -> TokenUsage:
        """See :meth:`flowcode.tinker_backend.TinkerBackend.token_usage`."""
        ...


def validate_train_config(cfg: RootConfig) -> None:
    """Reject configurations that cannot mean what they say, before anything is spent.

    Args:
        cfg: The composed run config.

    Raises:
        ValueError: On an incoherent combination or an out-of-range value. In particular
            ``train.on_policy_only=true`` together with ``train.replay.enabled=true``: see
            this module's docstring for why that is not merely suboptimal but wrong.
    """
    train_cfg = cfg.train
    if train_cfg.on_policy_only and train_cfg.replay.enabled:
        raise ValueError(
            "train.on_policy_only=true is incompatible with train.replay.enabled=true.\n"
            "on_policy_only reuses the SAMPLER's logprobs as the current policy's, which is "
            "only true for trajectories sampled from the current weights. Replayed "
            "trajectories came from an older policy, so their stored logprobs are stale and "
            "training on them silently regresses the balance conditions against the wrong "
            "log P_F.\n"
            "Fix it with either of:\n"
            "  train.replay.enabled=false      # cheapest: keeps the halved token bill\n"
            "  train.on_policy_only=false      # keeps replay, pays for the forward() oracle"
        )
    if train_cfg.steps <= 0:
        raise ValueError(f"train.steps must be positive, got {train_cfg.steps}")
    if train_cfg.groups_per_step <= 0 or train_cfg.group_size <= 0:
        raise ValueError(
            "train.groups_per_step and train.group_size must both be positive, got "
            f"{train_cfg.groups_per_step} and {train_cfg.group_size}"
        )
    if train_cfg.lr_schedule not in LR_SCHEDULES:
        raise ValueError(
            f"train.lr_schedule must be one of {list(LR_SCHEDULES)}, got {train_cfg.lr_schedule!r}"
        )
    if train_cfg.warmup_steps < 0:
        raise ValueError(f"train.warmup_steps must be non-negative, got {train_cfg.warmup_steps}")
    if train_cfg.policy_lr <= 0:
        raise ValueError(f"train.policy_lr must be positive, got {train_cfg.policy_lr}")
    if train_cfg.replay.enabled and not 0.0 <= train_cfg.replay.fraction < 1.0:
        raise ValueError(
            f"train.replay.fraction must be in [0, 1), got {train_cfg.replay.fraction}; it is "
            "the replayed SHARE of each batch, so 1.0 would mean never training on fresh "
            "rollouts at all"
        )


def learning_rate(step: int, base_lr: float, schedule: str, warmup_steps: int, steps: int) -> float:
    """The policy learning rate at ``step``.

    Warmup is linear over ``warmup_steps`` and runs from ``base_lr / warmup_steps`` up to
    ``base_lr`` — never from exactly zero, because Tinker rejects a non-positive learning
    rate and a first step that cannot run is a worse failure than a first step that is
    slightly too large.

    After warmup, ``progress`` runs 0 -> 1 across the remaining steps:

    * ``constant``: ``base_lr``.
    * ``linear``: ``base_lr * (1 - progress)``.
    * ``cosine``: ``base_lr * 0.5 * (1 + cos(pi * progress))``.

    Both decaying schedules reach exactly 0 at ``step == steps``, which is one past the
    last step actually taken (steps are 0-indexed), so the final step still trains.

    Args:
        step: Zero-based step index.
        base_lr: Peak learning rate, i.e. ``train.policy_lr``.
        schedule: One of :data:`LR_SCHEDULES`.
        warmup_steps: Linear warmup length; ``0`` disables warmup.
        steps: Total steps in the run.

    Returns:
        The learning rate for this step, always positive.

    Raises:
        ValueError: On an unknown schedule.
    """
    if schedule not in LR_SCHEDULES:
        raise ValueError(f"unknown lr_schedule {schedule!r}; expected one of {list(LR_SCHEDULES)}")
    if step < warmup_steps:
        return base_lr * float(step + 1) / float(warmup_steps)
    if schedule == "constant":
        return base_lr
    remaining = max(1, steps - warmup_steps)
    progress = min(1.0, max(0.0, (step - warmup_steps) / remaining))
    if schedule == "linear":
        return base_lr * (1.0 - progress)
    return base_lr * 0.5 * (1.0 + math.cos(math.pi * progress))


def _config_dict(cfg: RootConfig) -> dict[str, Any]:
    """The composed config as plain containers, for the wandb run config."""
    if isinstance(cfg, DictConfig):
        container = OmegaConf.to_container(cfg, resolve=True)
        if isinstance(container, dict):
            return {str(k): v for k, v in container.items()}
    return {}


def _grad_of(tensor: torch.Tensor) -> torch.Tensor:
    """A tensor's gradient, or an explicit zero when the loss did not depend on it.

    ``None`` here is legitimate — VarGrad contributes nothing for a group of one — and
    :meth:`~flowcode.tinker_backend.TinkerBackend.apply_gradient` requires a tensor per
    trajectory, so the zero has to be materialised rather than the trajectory dropped
    (dropping would misalign the batch).
    """
    return torch.zeros_like(tensor) if tensor.grad is None else tensor.grad


class Trainer:
    """Owns one training run: rollouts, replay, both optimisers, metrics and the bill.

    Args:
        cfg: The composed run config.
        backend: The Tinker bridge, or anything satisfying :class:`BackendLike`.
        env: The scoring environment.
        objective: The GFlowNet loss.
        tokenizer: The model's tokenizer, for rendering prompts and decoding completions.
        run_logger: Metrics sink; a no-op logger is used when omitted.
        train_tasks: Tasks to sample from. Defaults to the ``train`` half of
            ``env.tasks()``.
        eval_tasks: Held-out tasks. Defaults to the ``val`` half of ``env.tasks()``.
        rng: Seeded RNG for task selection and replay. Defaults to
            ``random.Random(cfg.seed)``.

    Raises:
        ValueError: If the config is incoherent (see :func:`validate_train_config`) or the
            task lists come out empty.
    """

    def __init__(
        self,
        cfg: RootConfig,
        backend: BackendLike,
        env: Environment,
        objective: Objective,
        tokenizer: ChatTokenizer,
        *,
        run_logger: RunLogger | None = None,
        train_tasks: Sequence[Task] | None = None,
        eval_tasks: Sequence[Task] | None = None,
        rng: random.Random | None = None,
        producer: TrajectoryProducer | None = None,
    ) -> None:
        validate_train_config(cfg)
        self.cfg = cfg
        self.backend = backend
        self.env = env
        self.objective = objective
        self.tokenizer = tokenizer
        self.run_logger: RunLogger = make_logger("none") if run_logger is None else run_logger
        self.rng = random.Random(cfg.seed) if rng is None else rng

        if train_tasks is None or eval_tasks is None:
            derived_train, derived_eval = self._split_tasks(env, cfg.seed)
            train_tasks = derived_train if train_tasks is None else train_tasks
            eval_tasks = derived_eval if eval_tasks is None else eval_tasks
        self.train_tasks: list[Task] = list(train_tasks)
        self.eval_tasks: list[Task] = list(eval_tasks)[:EVAL_MAX_TASKS]
        if not self.train_tasks:
            raise ValueError("the environment produced no training tasks")

        self.replay: ReplayBuffer | None = None
        if cfg.train.replay.enabled:
            self.replay = ReplayBuffer(
                capacity=cfg.train.replay.capacity, prioritize=cfg.train.replay.prioritize
            )

        # The flow optimiser is separate on purpose: log Z / log F are a handful of local
        # scalars fitting a quantity that spans dozens of nats, and at the policy LR they
        # lag so far behind that the balance residual measures log Z error, not policy
        # error. VarGrad has no such parameters and gets no optimiser at all.
        params = list(objective.parameters())
        self.flow_optimizer: torch.optim.Optimizer | None = (
            torch.optim.Adam(params, lr=cfg.train.flow_lr) if params else None
        )
        self.flow_parameters: list[torch.nn.Parameter] = params

        # When present, sampling and scoring run continuously in the background instead of
        # inside the step. Its lifecycle belongs to run(); constructing a Trainer does not
        # start it, so a caller driving step() by hand must start it themselves.
        self.producer = producer

        self.step_index = 0
        self.last_metrics: dict[str, float] = {}

    # ------------------------------------------------------------------------- task splits

    @staticmethod
    def _split_tasks(env: Environment, seed: int) -> tuple[list[Task], list[Task]]:
        """Carve a deterministic held-out slice out of whatever the environment offers.

        The :class:`~flowcode.envs.base.Environment` protocol exposes one flat task list —
        it has no notion of a validation split, and ``env.split`` already selected whatever
        the dataset calls one. So the eval set is a seeded slice of that list, disjoint from
        the training tasks and identical across processes and restarts (see
        :func:`flowcode.envs.datasets.split_tasks`).
        """
        tasks = list(env.tasks())
        if len(tasks) < 2:
            return tasks, []
        return (
            split_tasks(tasks, split="train", seed=seed),
            split_tasks(tasks, split="val", seed=seed),
        )

    def _pick_tasks(self) -> list[Task]:
        """Choose this step's prompts.

        Without replacement when the task set is big enough, with replacement otherwise —
        a fixture set of eight tasks and ``groups_per_step=8`` must still produce a full
        batch rather than raise.
        """
        k = self.cfg.train.groups_per_step
        if k <= len(self.train_tasks):
            return self.rng.sample(self.train_tasks, k)
        return [self.rng.choice(self.train_tasks) for _ in range(k)]

    # ------------------------------------------------------------------------------- costs

    def spend(self) -> CostEstimate:
        """Price what the backend has actually spent so far."""
        return from_usage(
            self.backend.token_usage(),
            self.backend.model_cfg.name,
            self.cfg.cost.price_overrides,
        )

    def budget(self) -> CostEstimate:
        """Price the whole run up front, from the config."""
        return estimate(self.cfg)

    # ------------------------------------------------------------------------------- steps

    async def rollout_batch(self, tasks: Sequence[Task], stats: RolloutStats) -> list[Trajectory]:
        """Sample and score one group per task at training temperature."""
        return await rollout(
            self.backend,
            self.env,
            self.tokenizer,
            tasks,
            self.cfg,
            num_samples=self.cfg.train.group_size,
            stats=stats,
        )

    async def _collect_fresh(self, metrics: dict[str, float]) -> list[Trajectory]:
        """This step's fresh trajectories, from the producer if there is one.

        With a producer, sampling and scoring have been running continuously since the
        run started and this only takes what is already finished — the step does not wait
        on generation at all unless the sampler has fallen behind. Without one, the old
        synchronous path runs: pick tasks, sample, score, all in series.

        Args:
            metrics: The step's metric dict, updated in place with whichever source's
                statistics apply.

        Returns:
            The fresh trajectories, group-contiguous.
        """
        if self.producer is not None:
            fresh = await self.producer.drain(self.cfg.train.groups_per_step)
            metrics.update(self.producer.stats.as_metrics())
            metrics["producer/queued_groups"] = float(self.producer.queued_groups)
            return fresh

        stats = RolloutStats()
        fresh = await self.rollout_batch(self._pick_tasks(), stats)
        metrics.update(stats.as_metrics())
        return fresh

    def _mix_replay(self, fresh: Sequence[Trajectory]) -> tuple[list[Trajectory], int]:
        """Draw the replayed share of the batch, then bank the fresh rollouts.

        ``replay.fraction`` is the replayed share of the *final* batch, so the number drawn
        is ``len(fresh) * f / (1 - f)``: at ``f=0.25`` a 64-sample rollout is topped up with
        21 replayed trajectories for a batch of 85, of which 24.7% is replay. Fresh
        rollouts are never discarded to hit the ratio — they have already been paid for.

        Returns:
            ``(batch, num_replayed)``.
        """
        buffer = self.replay
        if buffer is None:
            return list(fresh), 0
        fraction = float(self.cfg.train.replay.fraction)
        wanted = 0
        if fraction > 0.0 and fresh:
            wanted = round(len(fresh) * fraction / (1.0 - fraction))
        # Sample before adding: otherwise a quarter of the "off-policy" batch is a second
        # copy of trajectories already in it.
        replayed = buffer.sample(wanted, self.rng)
        buffer.add(fresh)
        return [*fresh, *replayed], len(replayed)

    async def _current_logprobs(self, batch: Sequence[Trajectory]) -> list[torch.Tensor]:
        """Per-token logprobs under the current policy, as autograd leaves."""
        if self.cfg.train.on_policy_only:
            # Legal only because the sampler was synced this step and nothing in the batch
            # came from a buffer; validate_train_config enforces the second half.
            return [
                torch.tensor(t.sampling_logprobs, dtype=torch.float32, requires_grad=True)
                for t in batch
            ]
        return await self.backend.compute_logprobs(batch)

    async def step(self) -> dict[str, float]:
        """Run one optimiser step.

        Returns:
            A flat metric dict: the objective's own metrics plus rollout, replay, batch,
            learning-rate, token and dollar figures.
        """
        cfg = self.cfg
        step = self.step_index
        metrics: dict[str, float] = {}

        if cfg.train.sync_sampler_every > 0 and step % cfg.train.sync_sampler_every == 0:
            await self.backend.sync_sampler()
            metrics["sampler_synced"] = 1.0

        fresh = await self._collect_fresh(metrics)
        if not fresh:
            # Every completion in the batch was degenerate. Nothing to train on, and
            # raising would throw away the whole run over one bad step.
            logger.warning("step %d produced no usable trajectories; skipping", step)
            metrics["skipped"] = 1.0
            self.step_index += 1
            return metrics

        batch, num_replayed = self._mix_replay(fresh)
        metrics["batch/size"] = float(len(batch))
        metrics["batch/num_fresh"] = float(len(fresh))
        metrics["batch/num_replayed"] = float(num_replayed)
        metrics.update(self._batch_metrics(fresh))
        if self.replay is not None:
            metrics.update({f"replay/{k}": v for k, v in self.replay.stats().items()})

        logprobs = await self._current_logprobs(batch)
        if self.flow_optimizer is not None:
            self.flow_optimizer.zero_grad(set_to_none=True)

        loss, loss_metrics = self.objective.loss(logprobs, batch)
        loss.backward()
        metrics.update(loss_metrics)

        grads = [_grad_of(lp) for lp in logprobs]
        lr = learning_rate(
            step,
            cfg.train.policy_lr,
            cfg.train.lr_schedule,
            cfg.train.warmup_steps,
            cfg.train.steps,
        )
        # Submit the gradient without draining it, THEN submit the optimiser step, so
        # Tinker batches both into one server clock cycle.
        push_metrics = await self.backend.apply_gradient(
            batch, grads, grad_scale=1.0 / len(batch), defer=True
        )
        optim_metrics = await self.backend.optim_step(lr, grad_clip_norm=cfg.train.grad_clip_norm)
        metrics.update({f"policy/{k}": v for k, v in push_metrics.items()})
        metrics.update({f"policy/{k}": v for k, v in optim_metrics.items()})
        metrics["lr"] = lr

        metrics.update(self._step_flow_params())
        metrics.update(self._usage_metrics())

        self.step_index += 1
        self.last_metrics = metrics
        return metrics

    def _step_flow_params(self) -> dict[str, float]:
        """Clip and step the client-side ``log Z`` / ``log F`` parameters."""
        if self.flow_optimizer is None:
            return {"flow/num_params": 0.0}
        grad_norm = 0.0
        if self.cfg.train.grad_clip_norm > 0.0:
            grad_norm = float(
                torch.nn.utils.clip_grad_norm_(
                    self.flow_parameters, self.cfg.train.grad_clip_norm
                ).item()
            )
        self.flow_optimizer.step()
        return {
            "flow/num_params": float(sum(p.numel() for p in self.flow_parameters)),
            "flow/grad_norm": grad_norm,
            "flow/lr": float(self.cfg.train.flow_lr),
        }

    @staticmethod
    def _batch_metrics(batch: Sequence[Trajectory]) -> dict[str, float]:
        """Pass rate, error mix and mode diversity over the fresh rollouts.

        Mode diversity is the metric a GFlowNet is supposed to win on: a reward-maximising
        policy collapses onto one solution per prompt, a GFlowNet should keep several. It
        is counted here, on temperature-sampled training groups, rather than at eval time —
        greedy decoding has exactly one mode by construction, so counting distinct
        solutions there would always report 1.0 and mean nothing.
        """
        if not batch:
            return {}
        passed = [bool(t.metadata.get("passed", False)) for t in batch]
        pass_fractions = [float(t.metadata.get("pass_fraction", 0.0)) for t in batch]

        by_task: dict[str, set[str]] = {}
        for trajectory in batch:
            if not trajectory.metadata.get("passed"):
                continue
            fingerprint = str(trajectory.metadata.get("solution_fingerprint", ""))
            if fingerprint:
                by_task.setdefault(trajectory.task_id, set()).add(fingerprint)
        num_tasks = len({t.task_id for t in batch})
        distinct = sum(len(v) for v in by_task.values())

        metrics = {
            "pass_rate": sum(passed) / len(passed),
            "pass_fraction_mean": sum(pass_fractions) / len(pass_fractions),
            "diversity/distinct_passing_solutions": float(distinct),
            "diversity/modes_per_task": distinct / num_tasks if num_tasks else 0.0,
            "diversity/tasks_with_a_solution": float(len(by_task)),
        }
        errors: dict[str, int] = {}
        for trajectory in batch:
            kind = trajectory.metadata.get("error")
            if kind:
                errors[str(kind)] = errors.get(str(kind), 0) + 1
        for kind, count in errors.items():
            metrics[f"error/{kind}"] = count / len(batch)
        return metrics

    def _usage_metrics(self) -> dict[str, float]:
        """Cumulative tokens and dollars, for the table's last two columns."""
        usage = self.backend.token_usage()
        spend = self.spend()
        metrics = {
            "tokens_total": float(usage.train_tokens + usage.billable_sample_tokens),
            "tokens_train": float(usage.train_tokens),
            "tokens_sample": float(usage.billable_sample_tokens),
        }
        total = spend.total_usd_per_run
        if total is not None:
            metrics["usd_total"] = total
        return metrics

    # -------------------------------------------------------------------------------- eval

    async def evaluate(self) -> dict[str, float]:
        """Greedily sample the held-out tasks and report the pass rate.

        Greedy (``temperature=0``, one sample per task) rather than a temperature sweep:
        this is the "did the policy get better at solving these" number, it must not move
        with the sampler's luck, and it costs one completion per task. Diversity is measured
        on the training rollouts instead — see :meth:`_batch_metrics`.

        Returns:
            ``eval/*`` metrics, empty when there is no held-out split.
        """
        if not self.eval_tasks:
            return {}
        stats = RolloutStats()
        trajectories = await rollout(
            self.backend,
            self.env,
            self.tokenizer,
            self.eval_tasks,
            self.cfg,
            num_samples=1,
            temperature=0.0,
            stats=stats,
        )
        if not trajectories:
            return {"eval/num_tasks": float(len(self.eval_tasks)), "eval/pass_rate": 0.0}
        passed = sum(1 for t in trajectories if t.metadata.get("passed"))
        pass_fraction = sum(float(t.metadata.get("pass_fraction", 0.0)) for t in trajectories)
        return {
            "eval/num_tasks": float(len(trajectories)),
            "eval/pass_rate": passed / len(trajectories),
            "eval/pass_fraction_mean": pass_fraction / len(trajectories),
            "eval/log_reward_mean": sum(t.log_reward for t in trajectories) / len(trajectories),
        }

    # -------------------------------------------------------------------------- checkpoints

    async def save_checkpoint(self, step: int) -> str | None:
        """Persist everything needed to resume: policy, flow parameters, replay, position.

        A backend that owns its model checkpoints itself and this additionally writes the
        trainer's own state alongside it (see :mod:`flowcode.checkpoint` for why the flow
        parameters and the replay buffer are not optional extras). The hosted backend has
        no such API, so that path falls back to ``save_weights_for_sampler`` through a
        documented attribute lookup and degrades to a warning when it is absent — which is
        the case for the offline fakes.

        A failed checkpoint must not end a run that is otherwise fine.

        Args:
            step: Step number, folded into the checkpoint name.

        Returns:
            The saved path, or ``None`` if the backend cannot checkpoint.
        """
        save_local = getattr(self.backend, "save_checkpoint", None)
        if save_local is not None:
            return self._save_local_checkpoint(save_local, step)
        client = getattr(self.backend, "_training_client", None)
        save = getattr(client, "save_weights_for_sampler_async", None)
        if save is None:
            logger.warning("backend %r cannot save checkpoints; skipping", type(self.backend))
            return None
        name = _NAME_SAFE.sub(
            "-", f"{self.objective.name}-{self.backend.model_cfg.name}-{step:06d}"
        )
        try:
            future = await save(name)
            response = await future.result_async() if hasattr(future, "result_async") else future
        except Exception as exc:
            logger.warning("checkpoint at step %d failed: %s", step, exc)
            return None
        path = getattr(response, "path", None)
        return None if path is None else str(path)

    def _save_local_checkpoint(self, save_local: Any, step: int) -> str | None:
        """Write the backend's checkpoint plus the trainer's own state beside it."""
        root = Path(getattr(self.cfg.backend, "checkpoint_dir", "checkpoints"))
        target = root / f"step-{step:06d}"
        try:
            save_local(str(target))
            save_run_state(
                target,
                RunState(
                    step_index=self.step_index,
                    policy_version=int(getattr(self.backend, "policy_version", 0)),
                    flow_parameters=[p.detach().cpu() for p in self.flow_parameters],
                    flow_optimizer=(
                        self.flow_optimizer.state_dict()
                        if self.flow_optimizer is not None
                        else None
                    ),
                    replay=list(self.replay) if self.replay is not None else [],
                    rng_state=self.rng.getstate(),
                    torch_rng_state=torch.get_rng_state(),
                    metadata={
                        "objective": self.objective.name,
                        "model": self.backend.model_cfg.name,
                    },
                ),
            )
        except Exception as exc:
            logger.warning("checkpoint at step %d failed: %s", step, exc)
            return None
        return str(target)

    def load_checkpoint(self, path: str) -> None:
        """Resume from a checkpoint written by :meth:`save_checkpoint`.

        Restores the policy through the backend and the flow parameters, replay buffer,
        step index and RNG state through :mod:`flowcode.checkpoint`. Strict about all of
        them: a resume that quietly restarts the LR schedule or reinitialises ``log Z``
        looks like a working run and is not.

        Args:
            path: A checkpoint directory.

        Raises:
            FileNotFoundError: If the checkpoint is incomplete.
            RuntimeError: If the backend cannot restore itself.
            ValueError: If the flow parameters do not match the objective.
        """
        load_local = getattr(self.backend, "load_checkpoint", None)
        if load_local is None:
            raise RuntimeError(
                f"backend {type(self.backend).__name__} cannot restore a checkpoint; only "
                "backends that own their model can."
            )
        load_local(path)
        state = load_run_state(path)
        restore_flow_parameters(self.flow_parameters, state.flow_parameters)
        if self.flow_optimizer is not None and state.flow_optimizer is not None:
            self.flow_optimizer.load_state_dict(state.flow_optimizer)
        if self.replay is not None:
            self.replay.clear()
            self.replay.add(state.replay)
        self.step_index = state.step_index
        if state.rng_state is not None:
            self.rng.setstate(state.rng_state)
        if state.torch_rng_state is not None:
            torch.set_rng_state(state.torch_rng_state)
        logger.info(
            "resumed from %s at step %d with %d replayed trajectories",
            path,
            self.step_index,
            len(state.replay),
        )

    # -------------------------------------------------------------------------- the run

    async def run(self) -> dict[str, float]:
        """Run the whole configured schedule, reporting the spend whatever happens.

        Returns:
            The last step's metrics.
        """
        cfg = self.cfg
        budget = self.budget()
        self.run_logger.log_text(
            f"[bold]flowcode[/bold] objective={self.objective.name} env={self.env.name} "
            f"model={self.backend.model_cfg.name} steps={cfg.train.steps} "
            f"tasks={len(self.train_tasks)} eval_tasks={len(self.eval_tasks)}"
        )
        self.run_logger.log_object(budget.render(title="estimated cost of this run"))

        if self.producer is not None:
            await self.producer.start()
            # Warm up before the first step so it does not block on an empty queue. Not
            # fatal if the timeout fires — drain() waits for one group either way; this
            # only keeps the first step from being an outlier in the metrics.
            queued = await self.producer.prefill(cfg.train.groups_per_step, timeout=600.0)
            self.run_logger.log_text(f"producer warmed up with {queued} group(s) queued")

        try:
            for _ in range(cfg.train.steps):
                step = self.step_index
                metrics = await self.step()

                evaluated = False
                if cfg.train.eval_every > 0 and (step + 1) % cfg.train.eval_every == 0:
                    metrics.update(await self.evaluate())
                    evaluated = True
                if cfg.train.checkpoint_every > 0 and (step + 1) % cfg.train.checkpoint_every == 0:
                    path = await self.save_checkpoint(step + 1)
                    if path is not None:
                        self.run_logger.log_text(f"checkpoint: {path}")

                # An eval always gets logged, even on a step the throttle would skip:
                # eval_every and log_every are independent, and a held-out pass rate that
                # was paid for and then dropped on the floor is the worst of both.
                if cfg.train.log_every > 0 and (step % cfg.train.log_every == 0 or evaluated):
                    self.run_logger.log(step, metrics)
                self.last_metrics = metrics
        finally:
            if self.producer is not None:
                await self.producer.stop()
            self._report_cost(budget)
            self.run_logger.close()
        return self.last_metrics

    def _report_cost(self, budget: CostEstimate) -> None:
        """Print what was actually spent next to what was predicted."""
        actual = self.spend()
        self.run_logger.log_object(actual.render(title="actual spend"))
        predicted = budget.total_usd_per_step
        spent = actual.total_usd_per_run
        if predicted is None or spent is None or self.step_index == 0:
            return
        expected_so_far = predicted * self.step_index
        ratio = spent / expected_so_far if expected_so_far > 0 else float("nan")
        self.run_logger.log_text(
            f"spent ${spent:,.4f} over {self.step_index} step(s); the estimate predicted "
            f"${expected_so_far:,.4f} ({ratio:.2f}x). A ratio far from 1.0 means "
            "conf/cost/default.yaml's prompt/completion length assumptions do not match "
            "this workload."
        )


def _instantiate_objective(cfg: RootConfig) -> Objective:
    """Build the objective from its ``_target_`` block."""
    objective = instantiate(cfg.objective)
    if not isinstance(objective, Objective):
        raise TypeError(
            f"objective={getattr(cfg.objective, 'name', '?')!r} instantiated to "
            f"{type(objective).__name__}, which does not satisfy the Objective protocol "
            "(loss / parameters / register_tasks)"
        )
    return objective


def _instantiate_env(cfg: RootConfig) -> Environment:
    """Build the environment from its ``_target_`` block."""
    env = instantiate(cfg.env)
    if not isinstance(env, Environment):
        raise TypeError(
            f"env={getattr(cfg.env, 'name', '?')!r} instantiated to {type(env).__name__}, "
            "which does not satisfy the Environment protocol (tasks / log_reward / "
            "batch_log_reward)"
        )
    return env


def _iter_task_ids(tasks: Sequence[Task]) -> Iterator[str]:
    return (task.task_id for task in tasks)


async def train(cfg: RootConfig) -> None:
    """Compose everything the loop needs and run it.

    Order matters in two places. The config is validated *before* the backend is created,
    so an incoherent run costs nothing; and ``objective.register_tasks`` is called before
    the flow optimiser exists, because growing a per-task table replaces its
    :class:`~torch.nn.Parameter` and orphans any optimiser state keyed on the old tensor
    (see :class:`flowcode.objectives.flows.ConditionalLogZ`).

    Args:
        cfg: The composed run config.

    Raises:
        ValueError: On an incoherent config.
        RuntimeError: If ``TINKER_API_KEY`` is unset.
    """
    validate_train_config(cfg)
    torch.manual_seed(cfg.seed)
    random.seed(cfg.seed)

    env = _instantiate_env(cfg)
    objective = _instantiate_objective(cfg)
    tasks = list(env.tasks())
    # Register the FULL task set, train and held-out alike: an eval batch reaching an
    # unregistered id would grow the table mid-run and invalidate the flow optimiser.
    objective.register_tasks(list(_iter_task_ids(tasks)))

    backend = await _build_backend(cfg)
    tokenizer = _tokenizer_of(backend)
    run_logger = make_logger(cfg.logger, config=_config_dict(cfg), name=f"{objective.name}")

    trainer = Trainer(
        cfg,
        backend,
        env,
        objective,
        tokenizer,
        run_logger=run_logger,
    )
    if cfg.train.producer.enabled:
        trainer.producer = TrajectoryProducer(
            backend,
            env,
            tokenizer,
            cfg,
            trainer.train_tasks,
            concurrency=cfg.train.producer.concurrency,
            queue_size=cfg.train.producer.queue_size,
            max_staleness=cfg.train.producer.max_staleness,
            rng=random.Random(cfg.seed + 1),
            env_workers=int(getattr(cfg.env, "workers", 8)),
        )
    await trainer.run()


async def _build_backend(cfg: RootConfig) -> BackendLike:
    """Construct the backend named by ``backend.kind``.

    Imported lazily in both branches: the hosted path needs ``tinker`` and an API key, the
    local path needs the ``local`` extra, and asking for one must not require the other.

    Args:
        cfg: The composed run config.

    Returns:
        A backend satisfying :class:`BackendLike`.

    Raises:
        ValueError: On an unknown ``backend.kind``.
    """
    kind = getattr(cfg.backend, "kind", "tinker")
    if kind == "tinker":
        return await TinkerBackend.create(cfg.model, get_api_key(), get_project_id())
    if kind == "local":
        from flowcode.local_backend import LocalBackend
        from flowcode.samplers import build_sampler

        sampler = build_sampler(
            cfg.sampler.mode,
            cfg.model.name,
            **_sampler_kwargs(cfg),
        )
        return LocalBackend.create(
            cfg.model,
            sampler=sampler,
            dtype=cfg.backend.dtype,
            lora_alpha=cfg.backend.lora_alpha,
            lora_dropout=cfg.backend.lora_dropout,
            micro_batch_size=cfg.backend.micro_batch_size,
            learning_rate=cfg.train.policy_lr,
            weight_decay=cfg.backend.weight_decay,
            gradient_checkpointing=cfg.backend.gradient_checkpointing,
            attn_implementation=cfg.backend.attn_implementation,
            adapter_dir=cfg.backend.adapter_dir,
            mixed_precision=cfg.backend.mixed_precision,
        )
    raise ValueError(f"backend.kind must be 'tinker' or 'local', got {kind!r}")


def _sampler_kwargs(cfg: RootConfig) -> dict[str, Any]:
    """The subset of ``sampler.*`` that applies to the selected mode.

    The two modes take disjoint knobs — a remote engine was configured when it was
    started — so passing everything through would make ``create`` reject valid configs.
    """
    if cfg.sampler.mode == "remote":
        token_env = cfg.sampler.auth_token_env
        return {
            "base_url": cfg.sampler.base_url,
            "api_key": os.environ.get(token_env) if token_env else None,
        }
    return {
        "max_lora_rank": max(cfg.sampler.max_lora_rank, cfg.model.lora_rank),
        "gpu_memory_utilization": cfg.sampler.gpu_memory_utilization,
        "max_model_len": cfg.sampler.max_model_len,
        "enable_prefix_caching": cfg.sampler.enable_prefix_caching,
        "tensor_parallel_size": cfg.sampler.tensor_parallel_size,
        "dtype": cfg.backend.dtype,
        "seed": cfg.seed,
    }


def _tokenizer_of(backend: object) -> ChatTokenizer:
    """Fetch the model's tokenizer from the backend.

    A backend that owns its model exposes a ``tokenizer`` property and is asked directly.
    ``TinkerBackend`` does not — it keeps its clients private and offers no tokenizer
    accessor — so the hosted path falls back to reaching through the training client. That
    lookup is asserted here rather than left to fail inside the first rollout. Typed
    ``object`` so the offline fakes stay usable without a cast.

    Raises:
        RuntimeError: If neither route produces a tokenizer.
    """
    own = getattr(backend, "tokenizer", None)
    if own is not None:
        return own  # ty: ignore[invalid-return-type]
    client = getattr(backend, "_training_client", None)
    get_tokenizer = getattr(client, "get_tokenizer", None)
    if get_tokenizer is None:
        raise RuntimeError(
            "the training client exposes no get_tokenizer(); flowcode renders prompts with "
            "the model's own chat template and cannot proceed without it"
        )
    tokenizer: ChatTokenizer = get_tokenizer()
    return tokenizer
